baseurl = "https://devmirror.com/" 
languageCode = "en-us"
title = "Devs mirror"
theme = "mediumish"
summaryLength = 25
copyright = ""
enableEmoji = true
publishDir = "public"
disqusShortname = "devmirror"
googleAnalytics = "UA-142145414-1"

[params]
  logo = "/images/logo.png"
  description ="the clean blog!"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Yury Chudnovsky"
  thumbnail = "/images/author.png"
  description = "Principal Developer"

[params.index]
  picture = "/images/author.png"
  title = "Hi, my name is Yury Chudnovsky"
  subtitle = "I'm a problem solver for IT companies"
  mdtext = '''
I'm a software engineer, architect, IT/HR manager and you name it \
with about 10 years of professional expirience in gaming, fintech, e-commerce industries

### Follow me:
'''
  alertbar = false

[params.social]
  #github = "<username>"
  linkedin = "yury-chudnovsky"
  #xing = "<username>"
  #medium = "<username>"
  facebook = "yury.chudnovsky"
  twitter = "yurachud"
  goodreads = "jurijsc"
  #instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about"
